web1:
  image: pauloborges/averell
  command: npm run start
  ports:
    - 8000:8000
  links:
    - mongo
web2:
  image: pauloborges/averell
  command: npm run start
  ports:
    - 8000:8000
  links:
    - mongo
web3:
  image: pauloborges/averell
  command: npm run start
  ports:
    - 8000:8000
  links:
    - mongo
web4:
  image: pauloborges/averell
  command: npm run start
  ports:
    - 8000:8000
  links:
    - mongo
mongo:
  image: mongo
lb:
  image: nginx
  volumes:
    - /etc/letsencrypt/archive/averell.madeatfareoffice.com:/etc/nginx/tls
    - /app/nginx.conf:/etc/nginx/nginx.conf
  links: 
    - web1
    - web2
    - web3
    - web4
