nginx:
  image: nginx
  ports: 
    - 443:443
    - 80:80
  volumes:
    - /etc/letsencrypt/archive/averell.madeatfareoffice.com:/etc/nginx/tls
    - /app/nginx.conf:/etc/nginx/nginx.conf
  links: 
    - web
web:
  image: pauloborges/averell
  command: npm run start
  links:
    - mongo
mongo:
  image: mongo
