web:
  image: pauloborges/averell
  command: npm run start
  ports:
    - 8000:8000
  links:
    - mongo
mongo:
  image: mongo
lb:
  image: nginx
  volumes:
     - /etc/letsencrypt/archive/averell.madeatfareoffice.com/:/etc/nginx/tls/
     - /app/ngnix.conf/:/etc/nginx/nginx.conf

