const otaCodes = {
	PHN: "Mobile phone",
	BYC: "Bike rack",
	LUG: "Luggage rack",
	SKR: "Ski rack",
	TRH: "Trailer hitch",
	CSI: "Infant child seat	Child seat determined by weight/age of child: 0-12 month/0-13Kg.",
	CSB: "Child toddler seat	Child seat determined by weight/age of child: 1-3 years / 9-18 Kg.",
	CST: "Booster seat	Child seat determined by weight/age of child: 4-7 years/15 – 30 Kg.",
	SNO: "Snow chains",
	HCR: "Hand control right",
	HCL: "Hand control left",
	NVS: "Navigational system",
	SNT: "Snow tires",
	BBS: "Baby stroller",
	SPN: "Spinner knob	Knob that is attached to the steering wheel and is intended to make steering with one hand less difficult.",
	CBF: "Cargo barrier front",
	CBB: "Cargo barrier rear",
	LTR: "Luggage trailer",
	CSR: "Satellite radio",
	SBE: "Seat belt extensions",
	SNP: "Winter package",
	SKV: "Ski equipped",
	DVD: "Portable DVD/CD/picture player",
	MMS: "Multimedia center",
	FLH: "Flag holder",
	HEL: "Motorcycle helmet",
	JRC: "Jerrycan	Metal/plastic container for storing or transporting fuel.",
	LRC: "Luggage roof case",
	NAV: "Hand-held navigation system",
	SBR: "Snow board rack",
	SKB: "Ski box	Rooftop ski box mounted on any rooof rack/crossbars.",
	SRK: "Surf rack",
	STC: "Scooter case",
	TEL: "Car telephone",
	TOL: "Toll payment tag/pass",
	WHC: "Wheelchair",
	RPS: "Road/congestion payment scheme	Sticker, which must be fixed to the inside of your windscreen, entitles you to drive on the motorway/Congestion Fee.",
	CBS: "Booster cushion	Booster seat for child under 135 cm or up to 12 years",
	JAC: "Security devices"
}

module.exports = otaCodes
